#!/bin/bash
#The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
#When only the parameter domain is provided, display information for its subdomains www, lb-01, web-01 and web-02 - in this specific order
#When passing domain and subdomain parameters, display information for the specified subdomain