#!/usr/bin/env bash
#The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
function digcheck {
	if [ "$#" -eq 2 ]
		then
			declare -a DOMAINS=("$2")
	else
		declare -a DOMAINS=("www" "lb-01" "web-01" "web-02")
	fi

	for D in "${DOMAINS[@]}"
	do
		DIG=$(dig +nocmd +noall +answer "$D.$1" | awk 'FNR==1 {print}')
		DREC=$(echo "$DIG" | awk '{print $(NF-1)}')
		DADR=$(echo "$DIG" | awk '{print $(NF-0)}')
		echo "The subdomain $D is a $DREC record and points to $DADR"	
	done
}

digcheck $1 $2
