#!/usr/bin/env bash
#installs nginx and sets redirect
apt-get update -y
apt-get -y install nginx
echo "Holberton School/n" > ~/temp.html
mv ~/temp.html /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page/n" > ~/temp.html
mv ~/temp.html /usr/share/nginx/html/404.html
sed -i "s|#error_page 404 /404.html;|error_page 404 /404.html;\nlocation /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}|" /etc/nginx/sites-enabled/default
sed -i 's|^server {|server {\nadd_header X-Served-By $hostname;\n|' /etc/nginx/sites-enabled/default
service nginx restart