#!/usr/bin/env bash
# mad libs /etc/passwd
while IFS=':' read -r USERNAME PASSWORD USER_ID GROUP_ID INFO HOME_DIRECTORY COMMAND
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < "/etc/passwd"
