#!/usr/bin/env bash
#installs nginx and creates welcome pag
ssh ubuntu@35.243.217.174 -i ~/.ssh/holberton 'apt-get -y install nginx'
ssh ubuntu@35.243.217.174 -i ~/.ssh/holberton 'echo "Holberton School/n" > ~/temp.html'
ssh ubuntu@35.243.217.174 -i ~/.ssh/holberton 'mv ~/temp.html /usr/share/nginx/html/index.html'
