#!/usr/bin/env bash
#installs nginx and creates welcome pag
apt-get update -y
apt-get -y install nginx
echo "Holberton School/n" > ~/temp.html
mv ~/temp.html /usr/share/nginx/html/index.html
service nginx start
