#!/usr/bin/env bash
# Bash script that configures an Ubuntu server 
cp /etc/hosts ~/hosts.new
sed -i -E s/^127.*\\tlocalhost/127.0.0.2\\tlocalhost/ ~/hosts.new
sed -i -E s/^[0-9].*\\tfacebook.com/8.8.8.8\\tfacebook.com/ ~/hosts.new
mv ~/hosts.new /etc/hosts

